# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Check for EESSI init shell scripts to load eessi software module in software.eessi.io
on:
  push:
    branches: [ "*-software.eessi.io" ]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        EESSI_VERSION:
        - 2023.06
        EESSI_SOFTWARE_SUBDIR_OVERRIDE:
        - x86_64/generic
      fail-fast: false
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Mount EESSI CernVM-FS pilot repository
          uses: cvmfs-contrib/github-action-cvmfs@55899ca74cf78ab874bdf47f5a804e47c198743c # v4.0
          with:
              cvmfs_config_package: https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
              cvmfs_http_proxy: DIRECT
              cvmfs_repositories: software.eessi.io
         
         - name: Clone assert.sh script
           run: git clone https://github.com/lehmannro/assert.sh.git

         - name: Prepare PROMPT variables
           run: |
              export BASH_PROMPT=$(bash -c 'source init/bash; echo "$PS1"')
              export ZSH_PROMPT=$(zsh -c 'source init/zsh; echo "$PS1"')
              export KSH_PROMPT=$(ksh -c 'source init/ksh; echo "$PS1"')
              export FISH_PROMPT=$(fish -c 'source init/fish; echo "$PS1"')

         - name: Run tests for available shells
           run: |
              .github/workflows/scripts/test_init_scripts.sh "bash" "zsh" "ksh" "fish"

